typography_spectrum: 0.05022173374891281
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7235552053898573
  lightness: 0.28344193659722805
  saturation: 0.35480262781493366
  rhythmicContrast: 0.29124879953451455
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.40973176108673215
analytics:
  google: null
  facebook: null
  twitter: null
name: Think.VR
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Think VR  '
purpose: []
